"""add reminded_expired_at and indexes

Revision ID: 376acb25f2fb
Revises: eaa17cd95ffe
Create Date: 2025-09-02 20:28:08.434577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376acb25f2fb'
down_revision: Union[str, None] = 'eaa17cd95ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
