"""reminder flags

Revision ID: 5cd19cbbfb51
Revises: 376acb25f2fb
Create Date: 2025-09-02 20:52:26.540629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd19cbbfb51'
down_revision: Union[str, None] = '376acb25f2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('reminded_3d_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('reminded_1d_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_subscriptions_reminded_1d_at'), 'subscriptions', ['reminded_1d_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_reminded_3d_at'), 'subscriptions', ['reminded_3d_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_reminded_expired_at'), 'subscriptions', ['reminded_expired_at'], unique=False)
    op.create_index('ix_subscriptions_status_ends_at', 'subscriptions', ['status', 'ends_at'], unique=False)
    op.create_index('ix_subscriptions_tg_id_status', 'subscriptions', ['tg_id', 'status'], unique=False)
    op.drop_column('subscriptions', 'last_notified_1d')
    op.drop_column('subscriptions', 'last_notified_3d')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_notified_3d', sa.DATETIME(), nullable=True))
    op.add_column('subscriptions', sa.Column('last_notified_1d', sa.DATETIME(), nullable=True))
    op.drop_index('ix_subscriptions_tg_id_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status_ends_at', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_expired_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_3d_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_1d_at'), table_name='subscriptions')
    op.drop_column('subscriptions', 'reminded_1d_at')
    op.drop_column('subscriptions', 'reminded_3d_at')
    # ### end Alembic commands ###
