"""Add winback fields to users

Revision ID: 7021de99409d
Revises: ba9031afc8f9
Create Date: 2025-09-03 19:23:35.110641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7021de99409d'
down_revision: Union[str, None] = 'ba9031afc8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('winback_3d_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('winback_7d_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('winback_30d_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'winback_30d_sent_at')
    op.drop_column('users', 'winback_7d_sent_at')
    op.drop_column('users', 'winback_3d_sent_at')
    # ### end Alembic commands ###
