"""Initial migration

Revision ID: ba9031afc8f9
Revises: 
Create Date: 2025-09-03 18:36:13.836097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9031afc8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('order_reference', sa.String(length=128), nullable=False),
    sa.Column('invoice_id', sa.String(length=128), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('tariff_code', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'expired', name='paymentstatus'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_reference'), 'payments', ['order_reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tg_id'), 'payments', ['tg_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_code', sa.String(length=8), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('reminded_3d_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_1d_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_ends_at'), 'subscriptions', ['ends_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_reminded_1d_at'), 'subscriptions', ['reminded_1d_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_reminded_3d_at'), 'subscriptions', ['reminded_3d_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_reminded_expired_at'), 'subscriptions', ['reminded_expired_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_status_ends_at', 'subscriptions', ['status', 'ends_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_tg_id'), 'subscriptions', ['tg_id'], unique=False)
    op.create_index('ix_subscriptions_tg_id_status', 'subscriptions', ['tg_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subscriptions_tg_id_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tg_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_status_ends_at', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_expired_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_3d_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reminded_1d_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_ends_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_tg_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_reference'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
